apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: gcr.io/in-activity-2/container-1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: persistent-storage
          mountPath: /sid_PV_dir
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: s8s-pvc
